Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "public_network"
    config.vm.provision "shell", inline:  "sudo apt-get update -y & curl -LO 'https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl' &  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
end