Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network: public_network
    config.vm.provision "docker" do |d|    
        d.pull_images "aldry1303/despesa"
        end
    end