Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network :forwarded_port, guest: PORT, host: PORT, host_ip: "192.168.56.1"
    config.vm.provision "docker" do |d|    
        d.pull_images "PROVIDER/IMAGE:TAGVERSION"
        config.vm.provision "shell", inline:  "docker run -p PORT:PORT -d PROVIDER/IMAGE "
        end
    end
